import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/src/components/navbar";
import Container from "@/src/components/container";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Container>{children}</Container>
      </body>
    </html>
  );
}
